Numpy exercise
===

This exercise is designed to get you familiarised with numpy and shows the most common operations that you will perform in the future.

You will need the Iris.csv file from the GitHub repositry to perform this exercise.

Write your code in the following way:
#################################<br>

Your code here
#################################

In [2]:
import numpy as np

In [9]:
A=np.arange(16)   #This creates a vector with values from 0 to 15.
print(A)

#Reshape A into a 4x4 numpy array and print the array
#################################
A = A.reshape((4,4))
print(A)
#################################

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Expected output:<br>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

In [11]:
#Create another array B which is made of square of each elements of B and print B.
#################################
B = A**2
print(A)
#################################

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


Expected output:<br>
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [23]:
#Create a numpy array of shape (28,28) whose values are chosen randomly from 0-255
#################################
x = np.random.randint(255, size = 28*28).reshape((28,28))
#print(x)
#################################

#Convert x into a vector (Make it of single dimension)
#################################
x = x.reshape((28*28,1))
#print(x)
#################################

#Add the number 1 at the start of x
# e.g.: If x is [3,2,5,7,5,...], new x should be [1,3,2,5,7,5,...]
#################################
x= np.insert(x,0,1,axis=0)
#print(x)
#################################

#Create  vector W of shape (785,10) whose values follow a normal distribution with mean=0 and standard dev=0.01
#################################
W = 0.01*np.random.randn(785,10)+0
#print(W)
#################################

#Multiply the 2 matrices W and x. (Keep in mind the shape of the two)
#################################
Z = W * x
print(W)
#################################

[[ 0.01345932  0.00148281 -0.00855355 ...,  0.01175962  0.02052337
  -0.00090683]
 [ 0.0117316   0.00343813  0.00241286 ...,  0.01073986  0.0049817
  -0.00116953]
 [ 0.0071013  -0.00271119  0.010471   ...,  0.00526494  0.00251226
   0.00852122]
 ..., 
 [ 0.01229335  0.00048914 -0.00154502 ..., -0.01289011  0.01577354
   0.00114057]
 [-0.00084359  0.01419987  0.00565947 ...,  0.0007715   0.00347778
  -0.00896613]
 [ 0.01253537 -0.00995752 -0.0001247  ...,  0.01106872  0.00690227
  -0.00057011]]


In [42]:
#Load the Iris.csv file into numpy array 'data' and shuffle the data.(The data array should contain rows in random order)
#################################
data = np.genfromtxt('/home/mohitvijayv/Desktop/QSTP-ML-master/python-assn/assn-02/Iris.csv', delimiter=',', invalid_raise = False)
#print(data)
#data = np.random.shuffle(data)
#################################
#dataset = genfromtxt(open('iris.csv','r'), delimiter='',"",invalid_raise = False)

#Create a numpy array X that contains the firts 4 columns of data. Keep the last column of data in numpy array y.
#################################
#X = np.array(data(:, 0:4))
#y = np.array(data(:, 4))
#################################

/home/mohitvijayv/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: ConversionWarning: Some errors were detected !
    Line #25 (got 3 columns instead of 1)
    Line #66 (got 5 columns instead of 1)
    Line #116 (got 3 columns instead of 1)
    Line #126 (got 3 columns instead of 1)
    Line #130 (got 3 columns instead of 1)
    Line #135 (got 3 columns instead of 1)
    Line #140 (got 3 columns instead of 1)
    Line #144 (got 3 columns instead of 1)
    Line #159 (got 2 columns instead of 1)
    Line #177 (got 3 columns instead of 1)
    Line #179 (got 3 columns instead of 1)
    Line #1692 (got 2 columns instead of 1)
    Line #1693 (got 3 columns instead of 1)
    Line #1694 (got 3 columns instead of 1)
    Line #1695 (got 3 columns instead of 1)
    Line #1696 (got 3 columns instead of 1)
    Line #1697 (got 3 columns instead of 1)
    Line #1704 (got 3 columns instead of 1)
    Line #1705 (got 3 columns instead of 1)
    Line #1706 (got 3 columns instead of 1)
    L

In [ ]:
# Print the following:
# 1) First 10 values of data
# 2) Last 10 values of data
# 3) All rows of X whose corresponding value in y is 2

#################################
print(np.array(data(0:10, :)))
print(np.array(data(-10:, :)))
for i in range(len(y)):
    if y[i] == 2:
        print(np.array(X(i, :)))
#################################

In [36]:
# Create a numpy array y1 of same length as y and number of columns 3.
length = y.shape
y1 = np.array
# Values of y1 are such that,
# If y contains 0, y1 should have (1,0,0)
# If y contains 1, y1 should have (0,1,0)
# If y contains 2, y1 should have (0,0,1)
# This type of encoding is known as one-hot encoding

(16,)
